package com.webShop.util;

public class Constants {
    public static final String REGISTRATION_SERVLET = "register";
    public static final String LOGIN_SERVLET = "login";
    public static final String LEAVE_SERVLET = "leave";
    public static final String FILTER_PRODUCTS_SERVLET = "filter";
    public static final String LOG_FILE_PATH = "/WEB-INF/logs/webShop.log";
    public static final String CAPTCHA_SERVLET = "captcha-generator";
    public static final String CART_SERVLET = "cart";
    public static final String BUY_CART_SERVLET = "buyCart";
    public static final String REGISTRATION_PAGE_PATH = "registrationPage.jsp";
    public static final String LOGIN_PAGE_PATH = "loginPage.jsp";
    public static final String PRODUCTS_PAGE_PATH = "productsPage.jsp";
    public static final String RESULT_PAGE_PATH = "resultPage.jsp";
    public static final String IMAGE = "image/";
    public static final String TEXT = "text/";
    public static final String TEXT_HTML = "text/html";
    public static final String SORT_BY_NAME_ASC = "by name ascending";
    public static final String SORT_BY_NAME_DESC = "by name descending";
    public static final String SORT_BY_PRICE_ASC = "by price ascending";
    public static final String SORT_BY_PRICE_DESC = "by price descending";
    public static final int DEFAULT_ID = -1;
    public static final int DEFAULT_COUNT = 1;
    public static final String COUNT = "count";
    public static final String JSON_TYPE = "application/json";
    public static final int STATUS_SUCCESS = 200;
    public static final int STATUS_FAIL = 400;
    public static final String TOTAL = "total";
    public static final String CART_PRICE = "cartPrice";
    public static final String PRICE_FORMAT = "%.2f";
    public static final String BUY_CART_PAGE_PATH = "buyCartPage.jsp";
    public static final String DATETIME_FORMAT = "dd.MM.yyyy HH:mm:ss";
    public static final String CONTENT_TYPE_HEADER = "Content-Type";
    public static final String ACCEPT_ENCODING_HEADER = "Accept-Encoding";
    public static final String CONTENT_ENCODING_HEADER = "Content-Encoding";
    public static final String GZIP = "gzip";
    public static final String ACCEPT_HEADER = "Accept";
    public static final String CURRENT_LOCALE = "currentLocale";
    public static final String ACCEPT_LANGUAGE = "accept-language";
}
